geonode.geoserver.acl.gsauth_client.exceptions
==============================================

.. py:module:: geonode.geoserver.acl.gsauth_client.exceptions

.. autoapi-nested-parse::

   GeoServer ACL

   GeoServer Access Control List API  # noqa: E501

   The version of the OpenAPI document: 1.0.0
   Generated by: https://openapi-generator.tech



Exceptions
----------

.. autoapisummary::

   geonode.geoserver.acl.gsauth_client.exceptions.OpenApiException
   geonode.geoserver.acl.gsauth_client.exceptions.ApiTypeError
   geonode.geoserver.acl.gsauth_client.exceptions.ApiValueError
   geonode.geoserver.acl.gsauth_client.exceptions.ApiAttributeError
   geonode.geoserver.acl.gsauth_client.exceptions.ApiKeyError
   geonode.geoserver.acl.gsauth_client.exceptions.ApiException
   geonode.geoserver.acl.gsauth_client.exceptions.NotFoundException
   geonode.geoserver.acl.gsauth_client.exceptions.UnauthorizedException
   geonode.geoserver.acl.gsauth_client.exceptions.ForbiddenException
   geonode.geoserver.acl.gsauth_client.exceptions.ServiceException


Functions
---------

.. autoapisummary::

   geonode.geoserver.acl.gsauth_client.exceptions.render_path


Module Contents
---------------

.. py:exception:: OpenApiException

   Bases: :py:obj:`Exception`


   The base exception class for all OpenAPIExceptions


.. py:exception:: ApiTypeError(msg, path_to_item=None, valid_classes=None, key_type=None)

   Bases: :py:obj:`OpenApiException`, :py:obj:`TypeError`


   The base exception class for all OpenAPIExceptions


   .. py:attribute:: path_to_item


   .. py:attribute:: valid_classes


   .. py:attribute:: key_type


   .. py:attribute:: full_msg


.. py:exception:: ApiValueError(msg, path_to_item=None)

   Bases: :py:obj:`OpenApiException`, :py:obj:`ValueError`


   The base exception class for all OpenAPIExceptions


   .. py:attribute:: path_to_item


   .. py:attribute:: full_msg


.. py:exception:: ApiAttributeError(msg, path_to_item=None)

   Bases: :py:obj:`OpenApiException`, :py:obj:`AttributeError`


   The base exception class for all OpenAPIExceptions


   .. py:attribute:: path_to_item


   .. py:attribute:: full_msg


.. py:exception:: ApiKeyError(msg, path_to_item=None)

   Bases: :py:obj:`OpenApiException`, :py:obj:`KeyError`


   The base exception class for all OpenAPIExceptions


   .. py:attribute:: path_to_item


   .. py:attribute:: full_msg


.. py:exception:: ApiException(status=None, reason=None, http_resp=None)

   Bases: :py:obj:`OpenApiException`


   The base exception class for all OpenAPIExceptions


   .. py:method:: __str__()

      Custom error messages for exception



.. py:exception:: NotFoundException(status=None, reason=None, http_resp=None)

   Bases: :py:obj:`ApiException`


   The base exception class for all OpenAPIExceptions


.. py:exception:: UnauthorizedException(status=None, reason=None, http_resp=None)

   Bases: :py:obj:`ApiException`


   The base exception class for all OpenAPIExceptions


.. py:exception:: ForbiddenException(status=None, reason=None, http_resp=None)

   Bases: :py:obj:`ApiException`


   The base exception class for all OpenAPIExceptions


.. py:exception:: ServiceException(status=None, reason=None, http_resp=None)

   Bases: :py:obj:`ApiException`


   The base exception class for all OpenAPIExceptions


.. py:function:: render_path(path_to_item)

   Returns a string representation of a path


